-Ihardware/src/design/riscy/include/
hardware/src/design/riscy/riscv_decoder.v
hardware/src/design/riscy/riscv_hwloop_regs.v
hardware/src/design/riscy/riscv_wrapper.v
hardware/src/design/riscy/riscv_core.v
hardware/src/design/riscy/cluster_clock_gating.sv
hardware/src/design/riscy/riscv_debug_unit.v
hardware/src/design/riscy/riscv_ooc_top_level_wrapper.sv
hardware/src/design/riscy/riscv_id_stage.v
hardware/src/design/riscy/riscv_fetch_fifo.v
hardware/src/design/riscy/riscv_if_stage.v
hardware/src/design/riscy/riscv_alu.v
hardware/src/design/riscy/riscv_prefetch_buffer.v
hardware/src/design/riscy/riscv_prefetch_L0_buffer.v
hardware/src/design/riscy/riscv_mult.v
hardware/src/design/riscy/riscv_apu_disp.v
hardware/src/design/riscy/riscv_int_controller.v
hardware/src/design/riscy/riscv_alu_div.v
hardware/src/design/riscy/aes_sbox.v
hardware/src/design/riscy/riscv_zkn.v
hardware/src/design/riscy/riscv_ex_stage.v
hardware/src/design/riscy/riscv_L0_buffer.v
hardware/src/design/riscy/riscv_register_file.v
hardware/src/design/riscy/riscv_controller.v
hardware/src/design/riscy/riscv_data_cache.v
hardware/src/design/riscy/riscv_load_store_unit.v
hardware/src/design/riscy/riscv_hwloop_controller.v
hardware/src/design/riscy/riscv_cs_registers.v
hardware/src/design/riscy/riscv_compressed_decoder.v

